import { navigateTo } from '../app/browserRouter';
import { DashboardHeader } from './dashboard/DashboardHeader';

export function DocumentationPage() {
  return (
    <main className="dashboard-page documentation-page">
      <div className="dashboard-content documentation-content">
        <DashboardHeader />
        <article className="documentation-panel" aria-labelledby="documentation-title">
          <header className="documentation-header">
            <button
              type="button"
              className="icon-button projects-back-button"
              aria-label="Back to dashboard"
              onClick={() => navigateTo('/dashboard')}
            >
              &lt;
            </button>
            <div>
              <h1 id="documentation-title">USE Documentation</h1>
              <p>Model UML structures, specify OCL constraints, and validate object snapshots with USE.</p>
            </div>
          </header>

          <section>
            <h2>1. Build or import a model</h2>
            <p>Create a project to start with an empty UML model, or use <strong>Open Existing</strong> to import a <code>.use</code> model file. If it imports other files, add those source files to the import dialog as well.</p>
            <p>The Class Diagram is the graphical editor for classes, attributes, operations, associations, generalizations, enumerations, and data types.</p>
          </section>

          <section>
            <h2>2. Describe the class model</h2>
            <p>Add classes first, then define attributes and operations in their property panels. Create associations between classifier ends and choose their multiplicities, roles, and aggregation kind where needed.</p>
            <p>Use the Generalizations tab to connect a subclass to its superclass. Inherited attributes and operations are read-only in the subclass; edit their defining superclass instead.</p>
          </section>

          <section>
            <h2>3. Specify OCL constraints</h2>
            <p>The OCL Editor contains the canonical USE model text generated by the backend. Add invariants to state conditions that every valid object snapshot must satisfy, and use operation contracts for preconditions and postconditions.</p>
            <pre aria-label="OCL invariant example"><code>{`context Account inv NonNegativeBalance:
  self.balance >= 0`}</code></pre>
            <p>Apply text changes in the editor to parse and type-check the model. A successful apply replaces the UML model and refreshes the Explorer and diagrams.</p>
          </section>

          <section>
            <h2>4. Create an object snapshot</h2>
            <p>Open the Object Diagram and add instances of your concrete classes. Provide values for stored attributes, including inherited attributes, then create links for association instances.</p>
            <p>Choose an object to edit its slots, navigate its associations, or invoke an available operation. The object node shows the effective attribute values for its full inheritance hierarchy.</p>
          </section>

          <section>
            <h2>5. Validate and iterate</h2>
            <p>Validation checks multiplicities, types, invariants, and operation contracts. Fix reported issues in the model or object snapshot, then refresh validation to confirm the result.</p>
            <p>Changes in the Class Diagram regenerate the canonical USE text. Object Diagram changes affect only the current snapshot, because object instances and links are not part of a USE model file.</p>
          </section>
        </article>
      </div>
    </main>
  );
}
